create PROCEDURE PRC_MERGE_TBL_DEPARTMENT_MDMS AS
BEGIN
    ------------UPDATE-------------------------------------------------------
    MERGE INTO TBL_DEPARTMENT T
    USING
        (SELECT MDMS_DEPARTMENT.C_CODE               AS MDMS_C_CODE,
                MDMS_DEPARTMENT.C_PEOPLE_TYPE        AS MDMS_C_PEOPLE_TYPE,
                MDMS_DEPARTMENT.E_ENABLED            AS MDMS_E_ENABLED,
                MDMS_DEPARTMENT.E_DELETED            AS MDMS_E_DELETED,
                MDMS_DEPARTMENT.C_CORRECTION         AS MDMS_C_CORRECTION,
                MDMS_DEPARTMENT.C_ALIGNMENT          AS MDMS_C_ALIGNMENT,
                MDMS_DEPARTMENT.C_END_DATE           AS MDMS_C_END_DATE,
                MDMS_DEPARTMENT.C_GHESMAT_CODE       AS MDMS_C_GHESMAT_CODE,
                MDMS_DEPARTMENT.C_GHESMAT_TITLE      AS MDMS_C_GHESMAT_TITLE,
                MDMS_DEPARTMENT.C_HOZE_CODE          AS MDMS_C_HOZE_CODE,
                MDMS_DEPARTMENT.C_HOZE_TITLE         AS MDMS_C_HOZE_TITLE,
                MDMS_DEPARTMENT.C_ISSUABLE           AS MDMS_C_ISSUABLE,
                MDMS_DEPARTMENT.C_LEGACY_CHANGE_DATE AS MDMS_C_LEGACY_CHANGE_DATE,
                MDMS_DEPARTMENT.C_LEGACY_CREATE_DATE AS MDMS_C_LEGACY_CREATE_DATE,
                MDMS_DEPARTMENT.C_MOAVENAT_CODE      AS MDMS_C_MOAVENAT_CODE,
                MDMS_DEPARTMENT.C_MOAVENAT_TITLE     AS MDMS_C_MOAVENAT_TITLE,
                MDMS_DEPARTMENT.C_NATURE             AS MDMS_C_NATURE,
                MDMS_DEPARTMENT.C_NEW_CODE           AS MDMS_C_NEW_CODE,
                MDMS_DEPARTMENT.C_OLD_CODE           AS MDMS_C_OLD_CODE,
                MDMS_DEPARTMENT.C_OMOR_CODE          AS MDMS_C_OMOR_CODE,
                MDMS_DEPARTMENT.C_OMOR_TITLE         AS MDMS_C_OMOR_TITLE,
                TR_PARENT.C_CODE                     AS MDMS_C_PARENT_CODE,
                MDMS_DEPARTMENT.C_START_DATE         AS MDMS_C_START_DATE,
                MDMS_DEPARTMENT.C_TITLE              AS MDMS_C_TITLE,
                MDMS_DEPARTMENT.C_TITLE_L            AS MDMS_C_TITLE_L,
                MDMS_DEPARTMENT.C_TYPE               AS MDMS_C_TYPE,
                MDMS_DEPARTMENT.C_USER               AS MDMS_C_USER,
                MDMS_DEPARTMENT.C_VAHED_CODE         AS MDMS_C_VAHED_CODE,
                MDMS_DEPARTMENT.C_VAHED_TITLE        AS MDMS_C_VAHED_TITLE,
                TR_PARENT.ID                         AS MDMS_C_PARENT,
                MDMS_DEPARTMENT.C_MOJTAME_CODE       AS MDMS_C_MOJTAME_CODE,
                MDMS_DEPARTMENT.C_MOJTAME_TITLE      AS MDMS_C_MOJTAME_TITLE,
                TR_DEPARTMENT.C_CODE                 AS TR_C_CODE,
                TR_DEPARTMENT.C_PEOPLE_TYPE          AS TR_C_PEOPLE_TYPE,
                TR_DEPARTMENT.E_ENABLED              AS TR_E_ENABLED,
                TR_DEPARTMENT.E_DELETED              AS TR_E_DELETED,
                TR_DEPARTMENT.C_CORRECTION           AS TR_C_CORRECTION,
                TR_DEPARTMENT.C_END_DATE             AS TR_C_END_DATE,
                TR_DEPARTMENT.C_GHESMAT_CODE         AS TR_C_GHESMAT_CODE,
                TR_DEPARTMENT.C_GHESMAT_TITLE        AS TR_C_GHESMAT_TITLE,
                TR_DEPARTMENT.C_HOZE_CODE            AS TR_C_HOZE_CODE,
                TR_DEPARTMENT.C_HOZE_TITLE           AS TR_C_HOZE_TITLE,
                TR_DEPARTMENT.C_ISSUABLE             AS TR_C_ISSUABLE,
                TR_DEPARTMENT.C_LEGACY_CHANGE_DATE   AS TR_C_LEGACY_CHANGE_DATE,
                TR_DEPARTMENT.C_LEGACY_CREATE_DATE   AS TR_C_LEGACY_CREATE_DATE,
                TR_DEPARTMENT.C_MOAVENAT_CODE        AS TR_C_MOAVENAT_CODE,
                TR_DEPARTMENT.C_MOAVENAT_TITLE       AS TR_C_MOAVENAT_TITLE,
                TR_DEPARTMENT.C_NATURE               AS TR_C_NATURE,
                TR_DEPARTMENT.C_NEW_CODE             AS TR_C_NEW_CODE,
                TR_DEPARTMENT.C_OLD_CODE             AS TR_C_OLD_CODE,
                TR_DEPARTMENT.C_OMOR_CODE            AS TR_C_OMOR_CODE,
                TR_DEPARTMENT.C_OMOR_TITLE           AS TR_C_OMOR_TITLE,
                TR_DEPARTMENT.C_PARENT_CODE          AS TR_C_PARENT_CODE,
                TR_DEPARTMENT.C_START_DATE           AS TR_C_START_DATE,
                TR_DEPARTMENT.C_TITLE                AS TR_C_TITLE,
                TR_DEPARTMENT.C_TITLE_L              AS TR_C_TITLE_L,
                TR_DEPARTMENT.C_TYPE                 AS TR_C_TYPE,
                TR_DEPARTMENT.C_USER                 AS TR_C_USER,
                TR_DEPARTMENT.C_VAHED_CODE           AS TR_C_VAHED_CODE,
                TR_DEPARTMENT.C_VAHED_TITLE          AS TR_C_VAHED_TITLE,
                TR_DEPARTMENT.C_MOJTAME_CODE         AS TR_C_MOJTAME_CODE,
                TR_DEPARTMENT.C_MOJTAME_TITLE        AS TR_C_MOJTAME_TITLE
         FROM (SELECT DP.*,
                      CASE
                          WHEN C_ACTIVE = 1
                              OR C_ACTIVE IS NULL THEN
                              NULL
                          WHEN C_ACTIVE = 0 THEN
                              74
                          END AS E_ENABLED,
                      CASE
                          WHEN C_DELETED = 0
                              OR C_DELETED IS NULL THEN
                              NULL
                          ELSE
                              75
                          END AS E_DELETED
               FROM DEV_MDMS.TBL_MD_DEPARTMENT DP) MDMS_DEPARTMENT
                  INNER JOIN TBL_DEPARTMENT TR_DEPARTMENT
                             ON (MDMS_DEPARTMENT.C_CODE = TR_DEPARTMENT.C_CODE AND
                                 MDMS_DEPARTMENT.C_PEOPLE_TYPE = TR_DEPARTMENT.C_PEOPLE_TYPE)
                  LEFT JOIN DEV_MDMS.TBL_MD_DEPARTMENT mdms_parent_ on MDMS_DEPARTMENT.c_parent = mdms_parent_.c_id
                  LEFT JOIN TBL_DEPARTMENT TR_PARENT
                            ON (mdms_parent_.C_CODE = TR_PARENT.C_CODE AND
                                mdms_parent_.C_PEOPLE_TYPE = TR_PARENT.C_PEOPLE_TYPE)

         WHERE TR_DEPARTMENT.C_TITLE <> MDMS_DEPARTMENT.C_TITLE
            OR TR_DEPARTMENT.C_ALIGNMENT <> MDMS_DEPARTMENT.C_ALIGNMENT
            OR (TR_DEPARTMENT.C_ALIGNMENT IS NULL
             AND MDMS_DEPARTMENT.C_ALIGNMENT IS NOT NULL)
            OR (TR_DEPARTMENT.C_ALIGNMENT IS NOT NULL
             AND MDMS_DEPARTMENT.C_ALIGNMENT IS NULL)
            OR TR_DEPARTMENT.C_CORRECTION <> MDMS_DEPARTMENT.C_CORRECTION
            OR (TR_DEPARTMENT.C_CORRECTION IS NULL
             AND MDMS_DEPARTMENT.C_CORRECTION IS NOT NULL)
            OR (TR_DEPARTMENT.C_CORRECTION IS NOT NULL
             AND MDMS_DEPARTMENT.C_CORRECTION IS NULL)
            OR TR_DEPARTMENT.C_END_DATE <> MDMS_DEPARTMENT.C_END_DATE
            OR (TR_DEPARTMENT.C_END_DATE IS NULL
             AND MDMS_DEPARTMENT.C_END_DATE IS NOT NULL)
            OR (TR_DEPARTMENT.C_END_DATE IS NOT NULL
             AND MDMS_DEPARTMENT.C_END_DATE IS NULL)
            OR TR_DEPARTMENT.C_GHESMAT_CODE <> MDMS_DEPARTMENT.C_GHESMAT_CODE
            OR (TR_DEPARTMENT.C_GHESMAT_CODE IS NULL
             AND MDMS_DEPARTMENT.C_GHESMAT_CODE IS NOT NULL)
            OR (TR_DEPARTMENT.C_GHESMAT_CODE IS NOT NULL
             AND MDMS_DEPARTMENT.C_GHESMAT_CODE IS NULL)
            OR TR_DEPARTMENT.C_GHESMAT_TITLE <> MDMS_DEPARTMENT.C_GHESMAT_TITLE
            OR (TR_DEPARTMENT.C_GHESMAT_TITLE IS NULL
             AND MDMS_DEPARTMENT.C_GHESMAT_TITLE IS NOT NULL)
            OR (TR_DEPARTMENT.C_GHESMAT_TITLE IS NOT NULL
             AND MDMS_DEPARTMENT.C_GHESMAT_TITLE IS NULL)
            OR TR_DEPARTMENT.C_HOZE_CODE <> MDMS_DEPARTMENT.C_HOZE_CODE
            OR (TR_DEPARTMENT.C_HOZE_CODE IS NULL
             AND MDMS_DEPARTMENT.C_HOZE_CODE IS NOT NULL)
            OR (TR_DEPARTMENT.C_HOZE_CODE IS NOT NULL
             AND MDMS_DEPARTMENT.C_HOZE_CODE IS NULL)
            OR TR_DEPARTMENT.C_HOZE_TITLE <> MDMS_DEPARTMENT.C_HOZE_TITLE
            OR (TR_DEPARTMENT.C_HOZE_TITLE IS NULL
             AND MDMS_DEPARTMENT.C_HOZE_TITLE IS NOT NULL)
            OR (TR_DEPARTMENT.C_HOZE_TITLE IS NOT NULL
             AND MDMS_DEPARTMENT.C_HOZE_TITLE IS NULL)
            OR TR_DEPARTMENT.C_ISSUABLE <> MDMS_DEPARTMENT.C_ISSUABLE
            OR (TR_DEPARTMENT.C_ISSUABLE IS NULL
             AND MDMS_DEPARTMENT.C_ISSUABLE IS NOT NULL)
            OR (TR_DEPARTMENT.C_ISSUABLE IS NOT NULL
             AND MDMS_DEPARTMENT.C_ISSUABLE IS NULL)
            OR TR_DEPARTMENT.C_LEGACY_CHANGE_DATE <> MDMS_DEPARTMENT.C_LEGACY_CHANGE_DATE
            OR (TR_DEPARTMENT.C_LEGACY_CHANGE_DATE IS NULL
             AND MDMS_DEPARTMENT.C_LEGACY_CHANGE_DATE IS NOT NULL)
            OR (TR_DEPARTMENT.C_LEGACY_CHANGE_DATE IS NOT NULL
             AND MDMS_DEPARTMENT.C_LEGACY_CHANGE_DATE IS NULL)
            OR TR_DEPARTMENT.C_LEGACY_CREATE_DATE <> MDMS_DEPARTMENT.C_LEGACY_CREATE_DATE
            OR (TR_DEPARTMENT.C_LEGACY_CREATE_DATE IS NULL
             AND MDMS_DEPARTMENT.C_LEGACY_CREATE_DATE IS NOT NULL)
            OR (TR_DEPARTMENT.C_LEGACY_CREATE_DATE IS NOT NULL
             AND MDMS_DEPARTMENT.C_LEGACY_CREATE_DATE IS NULL)
            OR TR_DEPARTMENT.C_MOAVENAT_CODE <> MDMS_DEPARTMENT.C_MOAVENAT_CODE
            OR (TR_DEPARTMENT.C_MOAVENAT_CODE IS NULL
             AND MDMS_DEPARTMENT.C_MOAVENAT_CODE IS NOT NULL)
            OR (TR_DEPARTMENT.C_MOAVENAT_CODE IS NOT NULL
             AND MDMS_DEPARTMENT.C_MOAVENAT_CODE IS NULL)
            OR TR_DEPARTMENT.C_NATURE <> MDMS_DEPARTMENT.C_NATURE
            OR (TR_DEPARTMENT.C_NATURE IS NULL
             AND MDMS_DEPARTMENT.C_NATURE IS NOT NULL)
            OR (TR_DEPARTMENT.C_NATURE IS NOT NULL
             AND MDMS_DEPARTMENT.C_NATURE IS NULL)
            OR TR_DEPARTMENT.C_NEW_CODE <> MDMS_DEPARTMENT.C_NEW_CODE
            OR (TR_DEPARTMENT.C_NEW_CODE IS NULL
             AND MDMS_DEPARTMENT.C_NEW_CODE IS NOT NULL)
            OR (TR_DEPARTMENT.C_NEW_CODE IS NOT NULL
             AND MDMS_DEPARTMENT.C_NEW_CODE IS NULL)
            OR TR_DEPARTMENT.C_OLD_CODE <> MDMS_DEPARTMENT.C_OLD_CODE
            OR (TR_DEPARTMENT.C_OLD_CODE IS NULL
             AND MDMS_DEPARTMENT.C_OLD_CODE IS NOT NULL)
            OR (TR_DEPARTMENT.C_OLD_CODE IS NOT NULL
             AND MDMS_DEPARTMENT.C_OLD_CODE IS NULL)
            OR TR_DEPARTMENT.C_OMOR_CODE <> MDMS_DEPARTMENT.C_OMOR_CODE
            OR (TR_DEPARTMENT.C_OMOR_CODE IS NULL
             AND MDMS_DEPARTMENT.C_OMOR_CODE IS NOT NULL)
            OR (TR_DEPARTMENT.C_OMOR_CODE IS NOT NULL
             AND MDMS_DEPARTMENT.C_OMOR_CODE IS NULL)
            OR TR_DEPARTMENT.C_OMOR_TITLE <> MDMS_DEPARTMENT.C_OMOR_TITLE
            OR (TR_DEPARTMENT.C_OMOR_TITLE IS NULL
             AND MDMS_DEPARTMENT.C_OMOR_TITLE IS NOT NULL)
            OR (TR_DEPARTMENT.C_OMOR_TITLE IS NOT NULL
             AND MDMS_DEPARTMENT.C_OMOR_TITLE IS NULL)
            OR TR_DEPARTMENT.C_PARENT_CODE <> MDMS_DEPARTMENT.C_PARENT_CODE
            OR (TR_DEPARTMENT.C_PARENT_CODE IS NULL
             AND MDMS_DEPARTMENT.C_PARENT_CODE IS NOT NULL)
            OR (TR_DEPARTMENT.C_PARENT_CODE IS NOT NULL
             AND MDMS_DEPARTMENT.C_PARENT_CODE IS NULL)
            OR TR_DEPARTMENT.C_START_DATE <> MDMS_DEPARTMENT.C_START_DATE
            OR (TR_DEPARTMENT.C_START_DATE IS NULL
             AND MDMS_DEPARTMENT.C_START_DATE IS NOT NULL)
            OR (TR_DEPARTMENT.C_START_DATE IS NOT NULL
             AND MDMS_DEPARTMENT.C_START_DATE IS NULL)
            OR TR_DEPARTMENT.C_TITLE <> MDMS_DEPARTMENT.C_TITLE
            OR (TR_DEPARTMENT.C_TITLE IS NULL
             AND MDMS_DEPARTMENT.C_TITLE IS NOT NULL)
            OR (TR_DEPARTMENT.C_TITLE IS NOT NULL
             AND MDMS_DEPARTMENT.C_TITLE IS NULL)
            OR TR_DEPARTMENT.C_TITLE_L <> MDMS_DEPARTMENT.C_TITLE_L
            OR (TR_DEPARTMENT.C_TITLE_L IS NULL
             AND MDMS_DEPARTMENT.C_TITLE_L IS NOT NULL)
            OR (TR_DEPARTMENT.C_TITLE_L IS NOT NULL
             AND MDMS_DEPARTMENT.C_TITLE_L IS NULL)
            OR TR_DEPARTMENT.C_TYPE <> MDMS_DEPARTMENT.C_TYPE
            OR (TR_DEPARTMENT.C_TYPE IS NULL
             AND MDMS_DEPARTMENT.C_TYPE IS NOT NULL)
            OR (TR_DEPARTMENT.C_TYPE IS NOT NULL
             AND MDMS_DEPARTMENT.C_TYPE IS NULL)
            OR TR_DEPARTMENT.C_USER <> MDMS_DEPARTMENT.C_USER
            OR (TR_DEPARTMENT.C_USER IS NULL
             AND MDMS_DEPARTMENT.C_USER IS NOT NULL)
            OR (TR_DEPARTMENT.C_USER IS NOT NULL
             AND MDMS_DEPARTMENT.C_USER IS NULL)
            OR TR_DEPARTMENT.C_VAHED_CODE <> MDMS_DEPARTMENT.C_VAHED_CODE
            OR (TR_DEPARTMENT.C_VAHED_CODE IS NULL
             AND MDMS_DEPARTMENT.C_VAHED_CODE IS NOT NULL)
            OR (TR_DEPARTMENT.C_VAHED_CODE IS NOT NULL
             AND MDMS_DEPARTMENT.C_VAHED_CODE IS NULL)
            OR TR_DEPARTMENT.C_VAHED_TITLE <> MDMS_DEPARTMENT.C_VAHED_TITLE
            OR (TR_DEPARTMENT.C_VAHED_TITLE IS NULL
             AND MDMS_DEPARTMENT.C_VAHED_TITLE IS NOT NULL)
            OR (TR_DEPARTMENT.C_VAHED_TITLE IS NOT NULL
             AND MDMS_DEPARTMENT.C_VAHED_TITLE IS NULL)
            OR TR_DEPARTMENT.E_DELETED <> MDMS_DEPARTMENT.E_DELETED
            OR (TR_DEPARTMENT.E_DELETED IS NULL
             AND MDMS_DEPARTMENT.E_DELETED IS NOT NULL)
            OR (TR_DEPARTMENT.E_DELETED IS NOT NULL
             AND MDMS_DEPARTMENT.E_DELETED IS NULL)
            OR TR_DEPARTMENT.E_ENABLED <> MDMS_DEPARTMENT.E_ENABLED
            OR (TR_DEPARTMENT.E_ENABLED IS NULL
             AND MDMS_DEPARTMENT.E_ENABLED IS NOT NULL)
            OR (TR_DEPARTMENT.E_ENABLED IS NOT NULL
             AND MDMS_DEPARTMENT.E_ENABLED IS NULL)
            OR TR_DEPARTMENT.F_PARENT <> MDMS_DEPARTMENT.C_PARENT
            OR (TR_DEPARTMENT.F_PARENT IS NULL
             AND MDMS_DEPARTMENT.C_PARENT IS NOT NULL)
            OR (TR_DEPARTMENT.F_PARENT IS NOT NULL
             AND MDMS_DEPARTMENT.C_PARENT IS NULL)
            OR TR_DEPARTMENT.C_MOJTAME_CODE <> MDMS_DEPARTMENT.C_MOJTAME_CODE
            OR (TR_DEPARTMENT.C_MOJTAME_CODE IS NULL
             AND MDMS_DEPARTMENT.C_MOJTAME_CODE IS NOT NULL)
            OR (TR_DEPARTMENT.C_MOJTAME_CODE IS NOT NULL
             AND MDMS_DEPARTMENT.C_MOJTAME_CODE IS NULL)
            OR TR_DEPARTMENT.C_MOJTAME_TITLE <> MDMS_DEPARTMENT.C_MOJTAME_TITLE
            OR (TR_DEPARTMENT.C_MOJTAME_TITLE IS NULL
             AND MDMS_DEPARTMENT.C_MOJTAME_TITLE IS NOT NULL)
            OR (TR_DEPARTMENT.C_MOJTAME_TITLE IS NOT NULL
             AND MDMS_DEPARTMENT.C_MOJTAME_TITLE IS NULL)
        )
            CHANGES_
    ON (CHANGES_.MDMS_C_CODE = T.C_CODE AND CHANGES_.MDMS_C_PEOPLE_TYPE = T.C_PEOPLE_TYPE)
    WHEN MATCHED THEN
        UPDATE
        SET T.N_VERSION            = T.N_VERSION + 1,
            T.C_ALIGNMENT          = CHANGES_.MDMS_C_ALIGNMENT,
            T.C_CORRECTION         = CHANGES_.MDMS_C_CORRECTION,
            T.C_END_DATE           = MDMS_C_END_DATE,
            T.C_GHESMAT_CODE       = MDMS_C_GHESMAT_CODE,
            T.C_GHESMAT_TITLE      = MDMS_C_GHESMAT_TITLE,
            T.C_HOZE_CODE          = MDMS_C_HOZE_CODE,
            T.C_HOZE_TITLE         = MDMS_C_HOZE_TITLE,
            T.C_ISSUABLE           = MDMS_C_ISSUABLE,
            T.C_LAST_MODIFIED_BY   = 'CHARGOON',
            T.C_LEGACY_CHANGE_DATE = MDMS_C_LEGACY_CHANGE_DATE,
            T.C_LEGACY_CREATE_DATE = MDMS_C_LEGACY_CREATE_DATE,
            T.C_MOAVENAT_CODE      = MDMS_C_MOAVENAT_CODE,
            T.C_MOAVENAT_TITLE     = MDMS_C_MOAVENAT_TITLE,
            T.C_NATURE             = MDMS_C_NATURE,
            T.C_NEW_CODE           = MDMS_C_NEW_CODE,
            T.C_OLD_CODE           = MDMS_C_OLD_CODE,
            T.C_OMOR_CODE          = MDMS_C_OMOR_CODE,
            T.C_OMOR_TITLE         = MDMS_C_OMOR_TITLE,
            T.C_PARENT_CODE        = MDMS_C_PARENT_CODE,
            T.C_START_DATE         = MDMS_C_START_DATE,
            T.C_TITLE              = MDMS_C_TITLE,
            T.C_TITLE_L            = MDMS_C_TITLE_L,
            T.C_TYPE               = MDMS_C_TYPE,
            T.C_USER               = MDMS_C_USER,
            T.C_VAHED_CODE         = MDMS_C_VAHED_CODE,
            T.C_VAHED_TITLE        = MDMS_C_VAHED_TITLE,
            T.D_LAST_MODIFIED_DATE = SYSDATE,
            T.E_DELETED            = MDMS_E_DELETED,
            T.E_ENABLED            = MDMS_E_ENABLED,
            T.F_PARENT             = MDMS_C_PARENT,
            T.C_MOJTAME_CODE       = MDMS_C_MOJTAME_CODE,
            T.C_MOJTAME_TITLE      = MDMS_C_MOJTAME_TITLE;

    --------------INSERT-----------------------------------------------------
    MERGE INTO TBL_DEPARTMENT T
    USING (
        SELECT MDMS_DEPARTMENT.C_CODE               AS MDMS_C_CODE,
               MDMS_DEPARTMENT.C_PEOPLE_TYPE        AS MDMS_C_PEOPLE_TYPE,
               MDMS_DEPARTMENT.E_ENABLED            AS MDMS_E_ENABLED,
               MDMS_DEPARTMENT.E_DELETED            AS MDMS_E_DELETED,
               MDMS_DEPARTMENT.C_CORRECTION         AS MDMS_C_CORRECTION,
               MDMS_DEPARTMENT.C_ALIGNMENT          AS MDMS_C_ALIGNMENT,
               MDMS_DEPARTMENT.C_END_DATE           AS MDMS_C_END_DATE,
               MDMS_DEPARTMENT.C_GHESMAT_CODE       AS MDMS_C_GHESMAT_CODE,
               MDMS_DEPARTMENT.C_GHESMAT_TITLE      AS MDMS_C_GHESMAT_TITLE,
               MDMS_DEPARTMENT.C_HOZE_CODE          AS MDMS_C_HOZE_CODE,
               MDMS_DEPARTMENT.C_HOZE_TITLE         AS MDMS_C_HOZE_TITLE,
               MDMS_DEPARTMENT.C_ISSUABLE           AS MDMS_C_ISSUABLE,
               MDMS_DEPARTMENT.C_LEGACY_CHANGE_DATE AS MDMS_C_LEGACY_CHANGE_DATE,
               MDMS_DEPARTMENT.C_LEGACY_CREATE_DATE AS MDMS_C_LEGACY_CREATE_DATE,
               MDMS_DEPARTMENT.C_MOAVENAT_CODE      AS MDMS_C_MOAVENAT_CODE,
               MDMS_DEPARTMENT.C_MOAVENAT_TITLE     AS MDMS_C_MOAVENAT_TITLE,
               MDMS_DEPARTMENT.C_NATURE             AS MDMS_C_NATURE,
               MDMS_DEPARTMENT.C_NEW_CODE           AS MDMS_C_NEW_CODE,
               MDMS_DEPARTMENT.C_OLD_CODE           AS MDMS_C_OLD_CODE,
               MDMS_DEPARTMENT.C_OMOR_CODE          AS MDMS_C_OMOR_CODE,
               MDMS_DEPARTMENT.C_OMOR_TITLE         AS MDMS_C_OMOR_TITLE,
               TR_PARENT.C_CODE                     AS MDMS_C_PARENT_CODE,
               MDMS_DEPARTMENT.C_START_DATE         AS MDMS_C_START_DATE,
               MDMS_DEPARTMENT.C_TITLE              AS MDMS_C_TITLE,
               MDMS_DEPARTMENT.C_TITLE_L            AS MDMS_C_TITLE_L,
               MDMS_DEPARTMENT.C_TYPE               AS MDMS_C_TYPE,
               MDMS_DEPARTMENT.C_USER               AS MDMS_C_USER,
               MDMS_DEPARTMENT.C_VAHED_CODE         AS MDMS_C_VAHED_CODE,
               MDMS_DEPARTMENT.C_VAHED_TITLE        AS MDMS_C_VAHED_TITLE,
               TR_PARENT.ID                         AS MDMS_C_PARENT,
               MDMS_DEPARTMENT.C_MOJTAME_CODE       AS MDMS_C_MOJTAME_CODE,
               MDMS_DEPARTMENT.C_MOJTAME_TITLE      AS MDMS_C_MOJTAME_TITLE
        FROM (
                 SELECT DP.*,
                        CASE
                            WHEN C_ACTIVE = 1
                                OR C_ACTIVE IS NULL THEN
                                NULL
                            WHEN C_ACTIVE = 0 THEN
                                74
                            END AS E_ENABLED,
                        CASE
                            WHEN C_DELETED = 0
                                OR C_DELETED IS NULL THEN
                                NULL
                            ELSE
                                75
                            END AS E_DELETED
                 FROM DEV_MDMS.TBL_MD_DEPARTMENT DP) MDMS_DEPARTMENT
                 LEFT JOIN TBL_DEPARTMENT TR_DEP
                           ON (MDMS_DEPARTMENT.C_CODE = TR_DEP.C_CODE AND
                               MDMS_DEPARTMENT.C_PEOPLE_TYPE = TR_DEP.C_PEOPLE_TYPE)
                 LEFT JOIN DEV_MDMS.TBL_MD_DEPARTMENT mdms_parent_ on MDMS_DEPARTMENT.c_parent = mdms_parent_.c_id
                 LEFT JOIN TBL_DEPARTMENT TR_PARENT
                           ON (mdms_parent_.C_CODE = TR_PARENT.C_CODE AND
                               mdms_parent_.C_PEOPLE_TYPE = TR_PARENT.C_PEOPLE_TYPE)

        WHERE TR_DEP.ID IS NULL) NEW_
    ON (NEW_.MDMS_C_CODE = T.C_CODE AND NEW_.MDMS_C_PEOPLE_TYPE = T.C_PEOPLE_TYPE)
    WHEN NOT MATCHED THEN
        INSERT (ID,
                C_CODE,
                N_VERSION,
                C_ALIGNMENT,
                C_CORRECTION,
                C_CREATED_BY,
                C_END_DATE,
                C_GHESMAT_CODE,
                C_GHESMAT_TITLE,
                C_HOZE_CODE,
                C_HOZE_TITLE,
                C_ISSUABLE,
                C_LAST_MODIFIED_BY,
                C_LEGACY_CHANGE_DATE,
                C_LEGACY_CREATE_DATE,
                C_MOAVENAT_CODE,
                C_MOAVENAT_TITLE,
                C_NATURE,
                C_NEW_CODE,
                C_OLD_CODE,
                C_OMOR_CODE,
                C_OMOR_TITLE,
                C_PARENT_CODE,
                C_PEOPLE_TYPE,
                C_START_DATE,
                C_TITLE,
                C_TITLE_L,
                C_TYPE,
                C_USER,
                C_VAHED_CODE,
                C_VAHED_TITLE,
                D_CREATED_DATE,
                D_LAST_MODIFIED_DATE,
                E_DELETED,
                E_ENABLED,
                F_PARENT,
                C_MOJTAME_CODE,
                C_MOJTAME_TITLE)
        VALUES (SEQ_DEPARTMENT_ID.NEXTVAL,
                NEW_.MDMS_C_CODE,
                0,
                NEW_.MDMS_C_ALIGNMENT,
                NEW_.MDMS_C_CORRECTION,
                'CHARGOON',
                NEW_.MDMS_C_END_DATE,
                NEW_.MDMS_C_GHESMAT_CODE,
                NEW_.MDMS_C_GHESMAT_TITLE,
                NEW_.MDMS_C_HOZE_CODE,
                NEW_.MDMS_C_HOZE_TITLE,
                NEW_.MDMS_C_ISSUABLE,
                NULL,
                NEW_.MDMS_C_LEGACY_CHANGE_DATE,
                NEW_.MDMS_C_LEGACY_CREATE_DATE,
                NEW_.MDMS_C_MOAVENAT_CODE,
                NEW_.MDMS_C_MOAVENAT_TITLE,
                NEW_.MDMS_C_NATURE,
                NEW_.MDMS_C_NEW_CODE,
                NEW_.MDMS_C_OLD_CODE,
                NEW_.MDMS_C_OMOR_CODE,
                NEW_.MDMS_C_OMOR_TITLE,
                NEW_.MDMS_C_PARENT_CODE,
                NEW_.MDMS_C_PEOPLE_TYPE,
                NEW_.MDMS_C_START_DATE,
                NEW_.MDMS_C_TITLE,
                NEW_.MDMS_C_TITLE_L,
                NEW_.MDMS_C_TYPE,
                NEW_.MDMS_C_USER,
                NEW_.MDMS_C_VAHED_CODE,
                NEW_.MDMS_C_VAHED_TITLE,
                SYSDATE,
                NULL,
                NEW_.MDMS_E_DELETED,
                NEW_.MDMS_E_ENABLED,
                NEW_.MDMS_C_PARENT,
                NEW_.MDMS_C_MOJTAME_CODE,
                NEW_.MDMS_C_MOJTAME_TITLE);

END;
/

