spring:
  application:
    name: training-web
  profiles:
    active: dev
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

nicico:
  oauth2:
    server:
      url: http://172.16.180.22
  welcome:
    url: /trainingMainDesktop
  upload:
    dir: c:\upload

---

spring:
  profiles: dev
  security:
    oauth2:
      client:
        registration:
          sso-login:
            provider: sso-provider
            client-id: TrainingDevClientId
            client-name: Training
            client-secret: password
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: user_info
        provider:
          sso-provider:
            authorization-uri: http://172.16.180.22/oauth/authorize
            token-uri: http://172.16.180.22/oauth/token
            jwkSetUri: http://172.16.180.22/.well-known/jwks.json
            user-info-uri: http://172.16.180.22/user/me
            user-name-attribute: username
server:
  servlet:
    context-path: /
  port: 10680

nicico:
  oauth2:
    token:
      cookie:
        domain: localhost
  rest-api:
    url: http://localhost:9090

logging:
  level:
    com.nicico: debug

---

spring:
  profiles: prod
  security:
    oauth2:
      client:
        registration:
          sso-login:
            provider: sso-provider
            client-id: TrainingClientId
            client-name: Training
            client-secret: password
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: user_info
        provider:
          sso-provider:
            authorization-uri: http://172.16.180.22/oauth/authorize
            token-uri: http://172.16.180.22/oauth/token
            jwkSetUri: http://172.16.180.22/.well-known/jwks.json
            user-info-uri: http://172.16.180.22/user/me
            user-name-attribute: username
server:
  servlet:
    context-path: /
  port: 10680

nicico:
  oauth2:
    token:
      cookie:
        domain: localhost
  rest-api:
    url: http://localhost:9090

logging:
  level:
    com.nicico: debug
