spring:
  datasource:
    url: jdbc:oracle:thin:@//10.1.254.131:1521/fgostardb
    username: PRD_TRAINING
    password: dWcOHoHBHZuPGs0vmZ8S
    hikari:
      maximum-pool-size: 60
      connection-timeout: 60000
  redis:
    host: apps.nicico.com
    password: nicico
  security:
    oauth2:
      client:
        registration:
          oserver:
            client-id: ${spring.application.name}
            client-secret: I1RrNI78A9WeaTH4MF0b
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: user_info
        provider:
          oserver:
            authorization-uri: http://apps.nicico.com/oauth/authorize
            token-uri: http://apps.nicico.com/oauth/token
            token-uri-swagger: https://apps.nicico.com/oauth/token
            user-info-uri: http://apps.nicico.com/user/info
            user-name-attribute: username

  cache:
    jcache:
      config: classpath:ehcache.xml
  config:
    activate:
      on-profile: Production

jasypt:
    encryptor:
      bean: stringEncryptor

nicico:
  server:
    url: http://devapp01.icico.net.ir/training
  security:
    sys-password: ENC(A7vRozXK8KtdP35y279QeRvnlzhFE23bRni6KJODwdQ=)

  minioQuestionsGroup: '614f0560d9bd82744565c05f'
  minioUrl: 'http://fms.nicico.com/fms/file'
  uploadMinioUrl: 'https://fms.nicico.com/fms/file'
  elsUrl: 'http://mobiles.nicico.com/api/training'
  hrmClient: 'https://apps.nicico.com/hrm/api/v1'
  sms: 'http://devops01.icico.net.ir'
  masterDataUrl: 'http://apps.nicico.com/master-data/api/v3'
  elsSmsUrl: 'https://mobiles.nicico.com'
  elsActuatorUrl: 'http://mobiles.nicico.com/actuator'
  fmsActuatorUrl: 'http://apps.nicico.com/fms/actuator'
  masterDataActuatorUrl: 'http://apps.nicico.com/master-data/actuator'
  hrmBackend: 'http://apps.nicico.com/hrm-backend/api/v1'
  trainingUrl: 'http://apps.nicico.com/training/'





  upload:
    dir: /var/nicico/${spring.application.name}/upload
  dirs:
    upload-class: /var/nicico/${spring.application.name}/upload/Tclass
    upload-class-deleted: /var/nicico/${spring.application.name}/upload/Tclass/deleted
    upload-teacher: /var/nicico/${spring.application.name}/upload/Teacher
    upload-teacher-deleted: /var/nicico/${spring.application.name}/upload/Teacher/deleted
    upload-Job: /var/nicico/${spring.application.name}/upload/Job
    upload-Job-deleted: /var/nicico/${spring.application.name}/upload/Job/deleted
    upload-JobGroup: /var/nicico/${spring.application.name}/upload/JobGroup
    upload-JobGroup-deleted: /var/nicico/${spring.application.name}/upload/JobGroup/deleted
    upload-PostGrade: /var/nicico/${spring.application.name}/upload/PostGrade
    upload-PostGrade-deleted: /var/nicico/${spring.application.name}/upload/PostGrade/deleted
    upload-PostGradeGroup: /var/nicico/${spring.application.name}/upload/PostGradeGroup
    upload-PostGradeGroup-deleted: /var/nicico/${spring.application.name}/upload/PostGradeGroup/deleted
    upload-PostGroup: /var/nicico/${spring.application.name}/upload/PostGroup
    upload-PostGroup-deleted: /var/nicico/${spring.application.name}/upload/PostGroup/deleted
    upload-Post: /var/nicico/${spring.application.name}/upload/Post
    upload-Post-deleted: /var/nicico/${spring.application.name}/upload/Post/deleted
    upload-person-img: /var/nicico/${spring.application.name}/upload/person/img
    upload-person-tmp: /var/nicico/${spring.application.name}/upload/person/img/tmp
    upload-bpmn: /var/nicico/${spring.application.name}/upload/bpmn
    upload-bpmn-img: /var/nicico/${spring.application.name}/upload/bpmn/img
    upload-TriningPost: /var/nicico/${spring.application.name}/upload/TriningPost
    upload-TriningPost-deleted: /var/nicico/${spring.application.name}/upload/TriningPost/deleted
    upload-question-bank: /var/nicico/${spring.application.name}/upload/questionBank
